// This PAC file will provide proxy config to Microsoft 365 services
//  using data from the public web service for all endpoints
function FindProxyForURL(url, host) {
    if (shExpMatch(host, "r1.res.office365.com") ||
        shExpMatch(host, "r3.res.office365.com") ||
        shExpMatch(host, "r4.res.office365.com") ||
        shExpMatch(host, "*.outlook.com") ||
        shExpMatch(host, "*.outlook.office.com") ||
        shExpMatch(host, "attachments.office.net") ||
        shExpMatch(host, "autodiscover.gulfaero.onmicrosoft.com") ||
        shExpMatch(host, "smtp.office365.com") ||
        shExpMatch(host, "*.protection.outlook.com") ||
        shExpMatch(host, "*.mail.protection.outlook.com") ||
        shExpMatch(host, "outlook.office.com") ||
        shExpMatch(host, "outlook.office365.com") ||
        shExpMatch(host, "*.sfbassets.com") ||
        shExpMatch(host, "*.urlp.sfbassets.com") ||
        shExpMatch(host, "skypemaprdsitus.trafficmanager.net") ||
        shExpMatch(host, "*.keydelivery.mediaservices.windows.net") ||
        shExpMatch(host, "*.msecnd.net") ||
        shExpMatch(host, "*.streaming.mediaservices.windows.net") ||
        shExpMatch(host, "ajax.aspnetcdn.com") ||
        shExpMatch(host, "mlccdn.blob.core.windows.net") ||
        shExpMatch(host, "aka.ms") ||
        shExpMatch(host, "amp.azure.net") ||
        shExpMatch(host, "*.msedge.net") ||
        shExpMatch(host, "compass-ssl.microsoft.com") ||
        shExpMatch(host, "*.mstea.ms") ||
        shExpMatch(host, "*.secure.skypeassets.com") ||
        shExpMatch(host, "mlccdnprod.azureedge.net") ||
        shExpMatch(host, "videoplayercdn.osi.office.net") ||
        shExpMatch(host, "*.skype.com") ||
        shExpMatch(host, "*.lync.com") ||
        shExpMatch(host, "*.teams.microsoft.com") ||
        shExpMatch(host, "teams.microsoft.com") ||
        shExpMatch(host, "*.broadcast.skype.com") ||
        shExpMatch(host, "broadcast.skype.com") ||
        shExpMatch(host, "*.wns.windows.com") ||
        shExpMatch(host, "admin.onedrive.com") ||
        shExpMatch(host, "officeclient.microsoft.com") ||
        shExpMatch(host, "g.live.com") ||
        shExpMatch(host, "oneclient.sfx.ms") ||
        shExpMatch(host, "*.sharepointonline.com") ||
        shExpMatch(host, "cdn.sharepointonline.com") ||
        shExpMatch(host, "privatecdn.sharepointonline.com") ||
        shExpMatch(host, "publiccdn.sharepointonline.com") ||
        shExpMatch(host, "spoprod-a.akamaihd.net") ||
        shExpMatch(host, "static.sharepointonline.com") ||
        shExpMatch(host, "*.svc.ms") ||
        shExpMatch(host, "gulfaero-files.sharepoint.com") ||
        shExpMatch(host, "gulfaero-myfiles.sharepoint.com") ||
        shExpMatch(host, "gulfaero.sharepoint.com") ||
        shExpMatch(host, "gulfaero-my.sharepoint.com") ||
        shExpMatch(host, "*.cdn.office.net") ||
        shExpMatch(host, "contentstorage.osi.office.net") ||
        shExpMatch(host, "*.onenote.com") ||
        shExpMatch(host, "*cdn.onenote.net") ||
        shExpMatch(host, "ajax.aspnetcdn.com") ||
        shExpMatch(host, "apis.live.net") ||
        shExpMatch(host, "cdn.optimizely.com") ||
        shExpMatch(host, "officeapps.live.com") ||
        shExpMatch(host, "www.onedrive.com") ||
        shExpMatch(host, "*.hip.live.com") ||
        shExpMatch(host, "*.microsoftonline.com") ||
        shExpMatch(host, "*.microsoftonline-p.com") ||
        shExpMatch(host, "*.msauth.net") ||
        shExpMatch(host, "*.msauthimages.net") ||
        shExpMatch(host, "*.msecnd.net") ||
        shExpMatch(host, "*.msftauth.net") ||
        shExpMatch(host, "*.msftauthimages.net") ||
        shExpMatch(host, "*.phonefactor.net") ||
        shExpMatch(host, "enterpriseregistration.windows.net") ||
        shExpMatch(host, "management.azure.com") ||
        shExpMatch(host, "policykeyservice.dc.ad.msft.net") ||
        shExpMatch(host, "suite.office.net") ||
        shExpMatch(host, "*.aria.microsoft.com") ||
        shExpMatch(host, "*.events.data.microsoft.com") ||
        shExpMatch(host, "*.o365weve.com") ||
        shExpMatch(host, "amp.azure.net") ||
        shExpMatch(host, "appsforoffice.microsoft.com") ||
        shExpMatch(host, "assets.onestore.ms") ||
        shExpMatch(host, "auth.gfx.ms") ||
        shExpMatch(host, "c1.microsoft.com") ||
        shExpMatch(host, "contentstorage.osi.office.net") ||
        shExpMatch(host, "dgps.support.microsoft.com") ||
        shExpMatch(host, "docs.microsoft.com") ||
        shExpMatch(host, "msdn.microsoft.com") ||
        shExpMatch(host, "platform.linkedin.com") ||
        shExpMatch(host, "prod.msocdn.com") ||
        shExpMatch(host, "shellprod.msocdn.com") ||
        shExpMatch(host, "support.content.office.net") ||
        shExpMatch(host, "support.microsoft.com") ||
        shExpMatch(host, "technet.microsoft.com") ||
        shExpMatch(host, "videocontent.osi.office.net") ||
        shExpMatch(host, "videoplayercdn.osi.office.net") ||
        shExpMatch(host, "*.office365.com") ||
        shExpMatch(host, "*.aadrm.com") ||
        shExpMatch(host, "*.azurerms.com") ||
        shExpMatch(host, "*.informationprotection.azure.com") ||
        shExpMatch(host, "ecn.dev.virtualearth.net") ||
        shExpMatch(host, "informationprotection.hosting.portal.azure.net") ||
        shExpMatch(host, "o15.officeredir.microsoft.com") ||
        shExpMatch(host, "officepreviewredir.microsoft.com") ||
        shExpMatch(host, "officeredir.microsoft.com") ||
        shExpMatch(host, "r.office.microsoft.com") ||
        shExpMatch(host, "ocws.officeapps.live.com") ||
        shExpMatch(host, "odc.officeapps.live.com") ||
        shExpMatch(host, "roaming.officeapps.live.com") ||
        shExpMatch(host, "activation.sls.microsoft.com") ||
        shExpMatch(host, "crl.microsoft.com") ||
        shExpMatch(host, "office15client.microsoft.com") ||
        shExpMatch(host, "officeclient.microsoft.com") ||
        shExpMatch(host, "insertmedia.bing.office.net") ||
        shExpMatch(host, "go.microsoft.com") ||
        shExpMatch(host, "support.office.com") ||
        shExpMatch(host, "ajax.aspnetcdn.com") ||
        shExpMatch(host, "officecdn.microsoft.com") ||
        shExpMatch(host, "officecdn.microsoft.com.edgesuite.net") ||
        shExpMatch(host, "*.entrust.net") ||
        shExpMatch(host, "*.geotrust.com") ||
        shExpMatch(host, "*.omniroot.com") ||
        shExpMatch(host, "*.public-trust.com") ||
        shExpMatch(host, "*.symcb.com") ||
        shExpMatch(host, "*.symcd.com") ||
        shExpMatch(host, "*.verisign.com") ||
        shExpMatch(host, "*.verisign.net") ||
        shExpMatch(host, "apps.identrust.com") ||
        shExpMatch(host, "cacerts.digicert.com") ||
        shExpMatch(host, "cert.int-x3.letsencrypt.org") ||
        shExpMatch(host, "crl.globalsign.com") ||
        shExpMatch(host, "crl.globalsign.net") ||
        shExpMatch(host, "crl.identrust.com") ||
        shExpMatch(host, "crl.microsoft.com") ||
        shExpMatch(host, "crl3.digicert.com") ||
        shExpMatch(host, "crl4.digicert.com") ||
        shExpMatch(host, "isrg.trustid.ocsp.identrust.com") ||
        shExpMatch(host, "mscrl.microsoft.com") ||
        shExpMatch(host, "ocsp.digicert.com") ||
        shExpMatch(host, "ocsp.globalsign.com") ||
        shExpMatch(host, "ocsp.msocsp.com") ||
        shExpMatch(host, "ocsp2.globalsign.com") ||
        shExpMatch(host, "ocspx.digicert.com") ||
        shExpMatch(host, "secure.globalsign.com") ||
        shExpMatch(host, "www.digicert.com") ||
        shExpMatch(host, "www.microsoft.com") ||
        shExpMatch(host, "*.config.office.net") ||
        shExpMatch(host, "*.manage.microsoft.com") ||
        shExpMatch(host, "*.office.com") ||
        shExpMatch(host, "cdnprod.myanalytics.microsoft.com") ||
        shExpMatch(host, "myanalytics.microsoft.com") ||
        shExpMatch(host, "myanalytics-gcc.microsoft.com") ||
        shExpMatch(host, "workplaceanalytics.cdn.office.net") ||
        shExpMatch(host, "workplaceanalytics.office.com") ||
        shExpMatch(host, "*.azure-apim.net") ||
        shExpMatch(host, "*.flow.microsoft.com") ||
        shExpMatch(host, "*.powerapps.com") ||
        shExpMatch(host, "activity.windows.com") ||
        shExpMatch(host, "ocsp.int-x3.letsencrypt.org") ||
        shExpMatch(host, "*.officeapps.live.com") ||
        shExpMatch(host, "*.online.office.com") ||
        shExpMatch(host, "office.live.com") ||
        shExpMatch(host, "*.msftidentity.com") ||
        shExpMatch(host, "*.msidentity.com") ||
        shExpMatch(host, "account.activedirectory.windowsazure.com") ||
        shExpMatch(host, "accounts.accesscontrol.windows.net") ||
        shExpMatch(host, "adminwebservice.microsoftonline.com") ||
        shExpMatch(host, "api.passwordreset.microsoftonline.com") ||
        shExpMatch(host, "autologon.microsoftazuread-sso.com") ||
        shExpMatch(host, "becws.microsoftonline.com") ||
        shExpMatch(host, "clientconfig.microsoftonline-p.net") ||
        shExpMatch(host, "companymanager.microsoftonline.com") ||
        shExpMatch(host, "device.login.microsoftonline.com") ||
        shExpMatch(host, "graph.microsoft.com") ||
        shExpMatch(host, "graph.windows.net") ||
        shExpMatch(host, "login.microsoft.com") ||
        shExpMatch(host, "login.microsoftonline.com") ||
        shExpMatch(host, "login.microsoftonline-p.com") ||
        shExpMatch(host, "login.windows.net") ||
        shExpMatch(host, "logincert.microsoftonline.com") ||
        shExpMatch(host, "loginex.microsoftonline.com") ||
        shExpMatch(host, "login-us.microsoftonline.com") ||
        shExpMatch(host, "nexus.microsoftonline-p.com") ||
        shExpMatch(host, "passwordreset.microsoftonline.com") ||
        shExpMatch(host, "provisioningapi.microsoftonline.com") ||
        shExpMatch(host, "*.compliance.microsoft.com") ||
        shExpMatch(host, "*.manage.office.com") ||
        shExpMatch(host, "*.protection.office.com") ||
        shExpMatch(host, "*.security.microsoft.com") ||
        shExpMatch(host, "compliance.microsoft.com") ||
        shExpMatch(host, "manage.office.com") ||
        shExpMatch(host, "protection.office.com") ||
        shExpMatch(host, "security.microsoft.com") ||
        shExpMatch(host, "*.portal.cloudappsecurity.com") ||
        shExpMatch(host, "account.office.net") ||
        shExpMatch(host, "admin.microsoft.com") ||
        shExpMatch(host, "home.office.com") ||
        shExpMatch(host, "portal.office.com") ||
        shExpMatch(host, "www.office.com") ||
        shExpMatch(host, "portal.microsoftonline.com")
    ) {
        return DIRECT;
    }
}